triggers: # RegEx
  - '[Tt].*[Ee].*[Aa].*[Mm].*[Uu].*[Pp]'

default-chat-format: '<%player_name%> {chat}' # Có hỗ trợ PlaceholderAPI.

# Từ dòng này trở đi KHÔNG. ĐƯỢC. EDIT. hoặc chết.
config-version: 1