# Các cài đặt tuỳ chỉnh cách plugin hoạt động. Thường thì cài đặt ở đây sẽ
# dùng chung cho toàn bộ detection ở dưới
GlobalSettings:
  # Cái này sẽ sneaky hơn tí, khi bị block thì vẫn sẽ gửi tin nhắn đến người
  # chơi có cùng IP với người vi phạm, còn những người chơi khác IP thì vẫn
  # block
  IPWideBlock: false
BlacklistDetection:
  enableRegex: true
  triggers: # RegEx
    - 't.*e.*a.*m.*u.*p'
    - 'miniflex?(jav)'

# Tính năng: Spam detection
SpamDetection:
  # Bật tính năng này?
  Enabled: true
  # Số lượng tin nhắn tối đa
  Count: 5
  # Trong khoảng thời gian bao nhiêu mili-giây?
  Time: 5000 # là 5 giây.

Locale:
  notify-format: "&f[&cNAID-CHAT-VIOLATION&f] %player%: %message%"

# Từ dòng này trở đi KHÔNG. ĐƯỢC. EDIT. hoặc chết.
config-version: 4